# Generated by Django 5.2.1 on 2025-06-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("monthly_income", models.IntegerField()),
                ("approved_limit", models.IntegerField()),
                ("phone_number", models.BigIntegerField(unique=True)),
                ("current_debt", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.CharField(max_length=20, unique=True)),
                ("loan_amount", models.FloatField()),
                ("tenure", models.IntegerField(help_text="Loan tenure in months")),
                ("interest_rate", models.FloatField()),
                ("monthly_repayment", models.FloatField()),
                ("emis_paid_on_time", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.customer"
                    ),
                ),
            ],
        ),
    ]
