# Generated by Django 5.2.1 on 2025-06-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="current_debt",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=301),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=301),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="myapp.customer",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure",
            field=models.IntegerField(),
        ),
    ]
