# Generated by Django 5.2.1 on 2025-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_customer_current_debt_remove_customer_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="customer",
            new_name="customer_ID",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="monthly_repayment",
            new_name="monthly_payment",
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=800),
        ),
    ]
