# Generated by Django 5.2.1 on 2025-06-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_customer_loan_customer_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="customer_ID",
            new_name="customer",
        ),
    ]
